### ISSUE TITLE
setup.py or pyproject.tomlの追加

### ISSUE THREAD

**Issue by lisphilar** [c60evaporator/seaborn_analyzer#4]
パッケージ及びQiita記事の作成ありがとうございます！
統計分布に疎いのでかなり勉強になります。

対応済でしたら申し訳ございませんが、pip install可能な形式で公開していただくことは可能でしょうか。
```Bash
pip install --upgrade "git+https://github.com/c60evaporator/seaborn_analyzer.git"
```
依存パッケージを列挙したsetup.pyファイル（あるいはpyproject.toml）の追加が必要になるかと思います。

パッケージ使用の敷居が低くなると思いますので、ご検討のほどよろしくお願い致します。

**Comment by c60evaporator** [comment]
@lisphilar さん
コメントありがとうございます。
一般人でもpipでインストールできるよう公開できるのですね！知らなかったです

現在
・回帰結果の可視化（相関分析、predict vs trueのプロット、予測結果ヒートマップ）
・分類結果の可視化（分類のヒートマップ表示）

についてもツールを作成中なので、これらが完了してきりの良いタイミングで、
pipで公開できるよう対応したいと思います
（ゴールデンウィークを目途で考えております）

**Comment by lisphilar** [comment]
@c60evaporator さん
ご返信ありがとうございます。

Google検索してもまとまった記事があまり見つからず、pandasなどの有名どころのGitHub repositoryを見てコピーして編集したほうが早いかもしれません...
なにか私の方で対応可能なことがあればいつでもご連絡ください。

また、相関分析などの可視化についても作成されるとのこと承知致しました。
楽しみにしています！

**Comment by c60evaporator** [comment]
備忘録：PyPIへの自作ライブラリ登録手順

## 1. __init.pyの追加
[seabornを参考に](https://github.com/mwaskom/seaborn/blob/master/seaborn/__init__.py)作成

## 2. ライセンスの追加
[参考URL](https://qiita.com/medi-y-sato/items/c3d5c357ab020290dccc)

## 3. README.rstを作成してsetup.pyのsetup()中のlong_descriptionに追加
これがPyPIにおけるドキュメントとなる

## 4. setup.pyの追加
[seaborn](https://github.com/mwaskom/seaborn/blob/master/setup.py)および[mlxtend](https://github.com/rasbt/mlxtend/blob/master/setup.py)を参考に作成

## 5. Twineを使ってPyPIに登録
[参考URL](https://qiita.com/shinichi-takii/items/e90dcf7550ef13b047b5)

※テスト用PyPIで動作確認→本番用にアップロードが望ましい

※Windowsでうまく.pypircが読み込めない場合は、[こちらのリンク](https://copdips.com/2019/07/troubleshooting-python-twine-cannot-upload-package-on-windows.html)を参考にPowerShellで

$env:HOME = '.pypircがあるディレクトリ名'

と打てばOK

## 6. API仕様書をSphinxで作成
[参考URL](https://qiita.com/futakuchi0117/items/4d3997c1ca1323259844)

## 7. API仕様書をgithub.ioにアップロード
[参考URL](https://sky-joker.github.io/github_sphinx_example/)

・参考URL
https://zenn.dev/karaage0703/articles/db8c663640c68b
https://blog.amedama.jp/entry/2017/12/31/175036

**Comment by c60evaporator** [comment]
@lisphilar さん
遅くなりましたが、下記のようにPyPIにアップロードしました
https://pypi.org/project/seaborn-analyzer/

pip install seaborn_analyzer

でインストールできるかと思います。
（アップロード後にアンダースコアが非推奨であることを知りました。PyPI上ではseaborn-analyzerに勝手に改名されてしましいましたが、pip install seaborn_analyzer、pip install seaborn-analyzerどちらでもインストールできるようです）

また、一点ご質問させて頂きたいのですが、下図のようなタブをGitHub上に表示させるためにはどのような手順を踏めば宜しいでしょうか？（PyPIのバージョン、ライセンス、Pythonバージョンが最低限表示できればありがたいです）
お手数をおかけしますが、ご教示頂けますと有難いです。
![image](https://user-images.githubusercontent.com/59557625/126800894-38c4395e-5fa1-4d3e-ae38-0439a45203ef.png)

**Comment by lisphilar** [comment]
@c60evaporator san,
ご連絡ありがとうございます！
pip installして使用できることを確認しました（取り急ぎ下記コード）。
```Python
# !pip install seaborn_analyzer
import seaborn as sns
from seaborn_analyzer.custom_hist_plot import hist
iris = sns.load_dataset("iris")
hist.plot_normality(iris, x='sepal_width', norm_hist=False, rounddigit=5)
```

> 下図のようなタブをGitHub上に表示させるためにはどのような手順を踏めば宜しいでしょうか？（PyPIのバージョン、ライセンス、Pythonバージョンが最低限表示できればありがたいです）

まず、README.mdに`[![画像名](画像のURL)](バッジをクリックした際の転送先URL)`の形式で書き込むと、repository内に画像を保存していなくても画像を表示されることができます。「画像名」は任意でOKです。「バッジをクリックした際の転送先URL」は、GitHub repositoryのLICENSEファイルのURLなど何でもOKです。「画像のURL」生成には[Shields.io](https://shields.io/category/platform-support)というバッジ作成サイトを使用しています。

以下、「画像のURL」生成方法です。

ライセンス:
ライセンスファイルがrepositoryにアップロードされているので、repositoryのURLをサイト[Shields.io](https://shields.io/category/platform-support)に入力してSuggest badgesをクリック頂くとバッジ画像とそのリンクが生成されます。
![Inkedキャプチャ_LI](https://user-images.githubusercontent.com/7270139/126870036-aff33ef3-a176-4490-8914-a40232196c82.jpg)


赤枠内（ライセンス表示用）をクリック、表示されるポップアップでCopy Badge URLを選択してバッジ画像のURLをコピーし、「画像のURL」としてご使用ください。
作成例 [![License](https://img.shields.io/github/license/c60evaporator/seaborn-analyzer)](https://github.com/c60evaporator/seaborn-analyzer/LICENSE)
```
[![License](https://img.shields.io/github/license/c60evaporator/seaborn-analyzer)](https://github.com/c60evaporator/seaborn-analyzer/LICENSE)
```

PyPIのバージョン：
Shields.ioのトップページから「Version」を選択して、下の方に行くと、PypI というバッジがあるのでリンクをクリック、パッケージ名を入力してリンクを作成してください。
<img width="463" alt="キャプチャ" src="https://user-images.githubusercontent.com/7270139/126869989-13a7cdef-a7cc-45c4-8014-9d926bfbd8b6.PNG">

Pythonのバージョン：
Shields.ioのトップページから「Platform & Version Support」を選択して、下の方に行くと、PypI - Python versionsというバッジがあるのでリンクをクリック、パッケージ名を入力してリンクを作成してください。
<img width="514" alt="キャプチャ" src="https://user-images.githubusercontent.com/7270139/126869884-cc61fb01-f173-4258-83c1-05857466b7e6.PNG">

**Comment by c60evaporator** [comment]
@lisphilar さん
ありがとうございます。おかげさまで無事バッジ画像をREADMEに貼る事ができました。
README自体の内容も整理して手直ししております。

動作確認もありがとうございます。

**Comment by c60evaporator** [comment]
本件、これにてCloseさせて頂きます
