### ISSUE TITLE
plot_roc_curve_multiclassメソッドのエラー

### ISSUE THREAD

**Issue by ghost** [c60evaporator/seaborn_analyzer#7]
はじめまして。このようなライブラリを探しておりましたので、ありがとうございました。

　plot_roc_curve_multiclassメソッドの実行例で紹介されている以下のサンプルコードをGoogle Colab上で実行すると、エラーが発生します。どのように対処したら宜しいでしょうか？　matplotlibのバージョンは3.5.2です。よろしくお願いいたします。

import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from seaborn_analyzer import classplot
# Load dataset
iris = sns.load_dataset("iris")
OBJECTIVE_VARIALBLE = 'species'  # Objective variable
USE_EXPLANATORY = ['petal_width', 'petal_length', 'sepal_width', 'sepal_length']  # Explantory variables
y = iris[OBJECTIVE_VARIALBLE].values
X = iris[USE_EXPLANATORY].values
# Add random noise features
random_state = np.random.RandomState(0)
n_samples, n_features = X.shape
X = np.c_[X, random_state.randn(n_samples, 10 * n_features)]
# Plot ROC curve in multiclass classification
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, random_state=42)
estimator = SVC(probability=True, random_state=42)
classplot.plot_roc_curve_multiclass(estimator, X_train, y_train, 
                                    X_test=X_test, y_test=y_test)
plt.plot([0, 1], [0, 1], label='Chance', alpha=0.8,
         lw=2, color='red', linestyle='--')
plt.legend(loc='lower right')

<matplotlib.legend.Legend at 0x7fc506323e90>
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/IPython/core/formatters.py](https://localhost:8080/#) in __call__(self, obj)
    332                 pass
    333             else:
--> 334                 return printer(obj)
    335             # Finally look for special method names
    336             method = get_real_method(obj, self.print_method)

3 frames
[/usr/local/lib/python3.7/dist-packages/matplotlib/backends/backend_agg.py](https://localhost:8080/#) in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    499         filename_or_obj : str or path-like or file-like
    500             The file to write to.
--> 501 
    502         metadata : dict, optional
    503             Metadata in the PNG file as key-value pairs of bytes or latin-1

ImportError: cannot import name '_png' from 'matplotlib' (/usr/local/lib/python3.7/dist-packages/matplotlib/__init__.py)

**Comment by c60evaporator** [comment]
@icots02 さん

Issues投稿頂きありがとうございます。
調査の結果原因が判明し、対策を実施致しました

## 原因

- seaborn-analyzerの依存パッケージ条件(setup.py)に、`matplotlib>=3.3.4`という条件を入れていた
- 上記により、seaborn-analyzerインストールと同時にmatplotlibのバージョンが強制的に3.3.4以上まで上げられる
- matplotlib3.3以上は、Python3.7と相性が悪くエラーが発生 ([こちらのリンク参照](https://qiita.com/mormor3g/questions/78cae51e51ced3664fa2))

## 対策
setup.pyに記載されている条件を、`matplotlib>=3.1.3`に変更

上記対策により、上記コードがColabで動作する事を確認いたしました。
