### ISSUE TITLE
ImportError: cannot import name 'plot_roc_curve' 

### ISSUE THREAD

**Issue by hima2b4** [c60evaporator/seaborn_analyzer#9]
seaborn-analyzer、とても重宝させていただいております。
Google colabで以下エラーが生じてしまいます。
原因がわかれば教えていただけるとありがたいです。

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-16-661e2568a38a>](https://localhost:8080/#) in <module>
      2 
      3 
----> 4 from seaborn_analyzer import CustomPairPlot
      5 
      6 cp = CustomPairPlot()

1 frames
[/usr/local/lib/python3.8/dist-packages/seaborn_analyzer/custom_class_plot.py](https://localhost:8080/#) in <module>
      5 import pandas as pd
      6 from scipy import stats
----> 7 from sklearn.metrics import auc, plot_roc_curve, roc_curve, RocCurveDisplay
      8 from sklearn.model_selection import KFold, LeaveOneOut, GroupKFold, LeaveOneGroupOut
      9 from sklearn.preprocessing import label_binarize

ImportError: cannot import name 'plot_roc_curve' from 'sklearn.metrics' (/usr/local/lib/python3.8/dist-packages/sklearn/metrics/__init__.py)

**Comment by hima2b4** [comment]
!pip install scikit-learn==1.1.3 にダウングレードすると、動作しました。
scikit-learnの変更による影響・・・なのでしょうか。

**Comment by c60evaporator** [comment]
遅くなりすみません。[こちらに記載されているように](https://scikit-learn.org/1.0/modules/generated/sklearn.metrics.plot_roc_curve.html)、plot_roc_curve()メソッドがscikit-learn1.2以上では削除されたことが原因のエラーのようです、代わりの[RocCurveDisplay.from_estimator()](https://scikit-learn.org/1.0/modules/generated/sklearn.metrics.RocCurveDisplay.html#sklearn.metrics.RocCurveDisplay.from_estimator)メソッドを使用するように修正いたしましたので（[version0.3.0](https://github.com/c60evaporator/seaborn-analyzer/releases/tag/v0.3.0)）、

```bash
pip install -U seaborn-analyzer
```

でアップデート頂ければ、scikit-learn==1.2.0以上でも動作するかと思います。
